spring:
  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST:user-db}:${POSTGRES_PORT:5432}/${POSTGRES_DB:user_service}
    username: ${POSTGRES_USER:admin}
    password: ${POSTGRES_PASSWORD:secret123}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yml
  data:
    redis:
      host: ${SPRING_DATA_REDIS_HOST:redis}
      port: ${SPRING_DATA_REDIS_PORT:6379}