spring:
  application:
    name: product-service
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
      enabled: true
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yml
  main:
    web-application-type: servlet
  datasource:
    url: jdbc:postgresql://product-db:5432/product_service
    username: admin
    password: secret123
    driver-class-name: org.postgresql.Driver
  elasticsearch:
    uris: http://elasticsearch:9200
  data:
    redis:
      host: redis
      port: 6379
  cache:
    type: redis
    redis:
      time-to-live: 600000ms #10dq
      cache-null-values: false
server:
  port: 8080

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      probes:
        enabled: true
logging:
  level:
    org.hibernate.SQL: OFF
    org.hibernate.type.descriptor.sql: OFF
    org.hibernate.orm.jdbc.bind: OFF